import argparse
import numpy as np
import galois

def to_plain_array(x):
    def row(row):
        return list(map(int, row))
    return list(map(row, x))

def generate_json(qs):
    print('{')
    for i, q in enumerate(qs):
        GF = galois.GF(q)
        x = GF(np.arange(q))
        add_table = np.add.outer(x, x)
        mul_table = np.multiply.outer(x, x)
        print(f'  "{q}": {{')
        print(f'    "add":\n      ', end='')
        print(str(to_plain_array(add_table)).replace('],', '],\n      '))
        print(',')
        print(f'    "mul":\n      ', end='')
        print(str(to_plain_array(mul_table)).replace('],', '],\n      '))
        if i == len(qs) - 1:
            print('  }')
        else:
            print('  },')
    print('}')


parser = argparse.ArgumentParser()
parser.add_argument('--js', default=False, action='store_true')
args = parser.parse_args()

if args.js:
    print('// AUTOGENERATED')
    print('// python galoistablegen.py --js > src/galoistable.js')
    print('export const table =')
generate_json([4, 8, 9, 16, 25, 27, 32])
if args.js:
    print(';')
